[book]
authors = ["Jérémie Astor", "Pranav Joglekar", "Amber Zeller"]
title = "Gwion"
description = "Tutorial and reference for gwion"
language = "en"

[output.html]
default-theme = "rust"
additional-css = ["custom.css", "ansi2html.css"]
git-repository-url ="https://github.com/fennecdjay/Gwion"
site-url = "/Gwion/"

[output.html.fold]
enable = true
level = 0

[output.html.search]
use-boolean-and = true
boost-title = 3
boost-hierarchy = 2
boost-paragraph = 1
